INSERT INTO AUTHOR VALUES (1, 'United States', 'author1@example.com', 'Author One');
INSERT INTO AUTHOR VALUES (2, 'Canada', 'author2@example.com', 'Author Two');
INSERT INTO AUTHOR VALUES (3, 'United Kingdom', 'author3@example.com', 'Author Three');
INSERT INTO AUTHOR VALUES (4, 'Australia', 'author4@example.com', 'Author Four');
INSERT INTO AUTHOR VALUES (5, 'Germany', 'author5@example.com', 'Author Five');
INSERT INTO AUTHOR VALUES (6, 'France', 'author6@example.com', 'Author Six');
INSERT INTO AUTHOR VALUES (7, 'Japan', 'author7@example.com', 'Author Seven');
INSERT INTO AUTHOR VALUES (8, 'China', 'author8@example.com', 'Author Eight');
INSERT INTO AUTHOR VALUES (9, 'India', 'author9@example.com', 'Author Nine');
INSERT INTO AUTHOR VALUES (10, 'Brazil', 'author10@example.com', 'Author Ten');
INSERT INTO AUTHOR VALUES (11, 'Argentina', 'author11@example.com', 'Author Eleven');
INSERT INTO AUTHOR VALUES (12, 'Colombia', 'author12@example.com', 'Author Twelve');
INSERT INTO AUTHOR VALUES (13, 'Netherlands', 'author13@example.com', 'Author Thirteen');
INSERT INTO AUTHOR VALUES (14, 'Spain', 'author14@example.com', 'Author Fourteen');
INSERT INTO AUTHOR VALUES (15, 'Sweden', 'author15@example.com', 'Author Fifteen');
INSERT INTO AUTHOR VALUES (16, 'Italy', 'author16@example.com', 'Author Sixteen');
INSERT INTO AUTHOR VALUES (17, 'Russia', 'author17@example.com', 'Author Seventeen');
INSERT INTO AUTHOR VALUES (18, 'South Korea', 'author18@example.com', 'Author Eighteen');
INSERT INTO AUTHOR VALUES (19, 'Mexico', 'author19@example.com', 'Author Nineteen');
INSERT INTO AUTHOR VALUES (20, 'Indonesia', 'author20@example.com', 'Author Twenty');
INSERT INTO AUTHOR VALUES (21, 'Nigeria', 'author21@example.com', 'Author Twenty One');
INSERT INTO AUTHOR VALUES (22, 'Egypt', 'author22@example.com', 'Author Twenty Two');
INSERT INTO AUTHOR VALUES (23, 'Philippines', 'author23@example.com', 'Author Twenty Three');
INSERT INTO AUTHOR VALUES (24, 'Vietnam', 'author24@example.com', 'Author Twenty Four');
INSERT INTO AUTHOR VALUES (25, 'Bangladesh', 'author25@example.com', 'Author Twenty Five');
INSERT INTO AUTHOR VALUES (26, 'Turkey', 'author26@example.com', 'Author Twenty Six');
INSERT INTO AUTHOR VALUES (27, 'Thailand', 'author27@example.com', 'Author Twenty Seven');
INSERT INTO AUTHOR VALUES (28, 'Poland', 'author28@example.com', 'Author Twenty Eight');
INSERT INTO AUTHOR VALUES (29, 'Argentina', 'author29@example.com', 'Author Twenty Nine');
INSERT INTO AUTHOR VALUES (30, 'Ukraine', 'author30@example.com', 'Author Thirty');
INSERT INTO AUTHOR VALUES (31, 'Saudi Arabia', 'author31@example.com', 'Author Thirty One');
INSERT INTO AUTHOR VALUES (32, 'Malaysia', 'author32@example.com', 'Author Thirty Two');
INSERT INTO AUTHOR VALUES (33, 'Czech Republic', 'author33@example.com', 'Author Thirty Three');
INSERT INTO AUTHOR VALUES (34, 'Belgium', 'author34@example.com', 'Author Thirty Four');
INSERT INTO AUTHOR VALUES (35, 'Greece', 'author35@example.com', 'Author Thirty Five');
INSERT INTO AUTHOR VALUES (36, 'Portugal', 'author36@example.com', 'Author Thirty Six');
INSERT INTO AUTHOR VALUES (37, 'Hungary', 'author37@example.com', 'Author Thirty Seven');
INSERT INTO AUTHOR VALUES (38, 'Switzerland', 'author38@example.com', 'Author Thirty Eight');
INSERT INTO AUTHOR VALUES (39, 'Austria', 'author39@example.com', 'Author Thirty Nine');
INSERT INTO AUTHOR VALUES (40, 'United Arab Emirates', 'author40@example.com', 'Author Forty');

INSERT INTO Book VALUES (1, 20, '978-0007470476', 'AVAILABLE', 'The Hitchhiker''s Guide to the Galaxy');
INSERT INTO Book VALUES (2, 30, '978-0385492336','AVAILABLE', 'Dune');
INSERT INTO Book VALUES (3, 25, '978-0060928254','AVAILABLE', 'The Lord of the Rings: The Fellowship of the Ring');
INSERT INTO Book VALUES (4, 15, '978-0375402584','AVAILABLE', 'The Hunger Games');
INSERT INTO Book VALUES (5, 35, '978-0316767944','AVAILABLE', 'Harry Potter and the Sorcerer''s Stone');
INSERT INTO Book VALUES (6, 20, '978-0440470428','AVAILABLE', 'The Curious Incident of the Dog in the Night-Time');
INSERT INTO Book VALUES (7, 15, '978-0310296501','AVAILABLE', 'The Perks of Being a Wallflower');
INSERT INTO Book VALUES (8, 25, '978-0316196333','AVAILABLE', 'A Game of Thrones');
INSERT INTO Book VALUES (9, 15, '978-0385533258', 'AVAILABLE','The Fault in Our Stars');
INSERT INTO Book VALUES (10, 30, '978-1400050766','AVAILABLE', '1984');
INSERT INTO Book VALUES (11, 15, '978-0141320290','AVAILABLE', 'The Handmaid''s Tale');
INSERT INTO Book VALUES (12, 25, '978-0345513274','AVAILABLE', 'The Book Thief');
INSERT INTO Book VALUES (13, 20, '978-0451527822','AVAILABLE', 'To Kill a Mockingbird');
INSERT INTO Book VALUES (14, 15, '978-0156027300','AVAILABLE', 'The Giver');
INSERT INTO Book VALUES (15, 30, '978-0316766668','AVAILABLE', 'Pride and Prejudice');
INSERT INTO Book VALUES (16, 20, '978-0451526665','AVAILABLE', 'Little Women');
INSERT INTO Book VALUES (17, 25, '980-3855333258','AVAILABLE', 'The Alchemist');
INSERT INTO Book VALUES (18, 15, '978-0312424567','AVAILABLE', 'The Absolutely True Diary of a Part-Time Indian');
INSERT INTO Book VALUES (19, 30, '978-1442401237','AVAILABLE', 'The Martian');
INSERT INTO Book VALUES (20, 25, '978-0375823336', 'AVAILABLE','The Hate U Give');
INSERT INTO Book VALUES (21, 15, '978-0385534836', 'AVAILABLE','Wonder');
INSERT INTO Book VALUES (22, 25, '978-1423110726','AVAILABLE', 'The Color Purple');
INSERT INTO Book VALUES (23, 20, '978-1534440022', 'AVAILABLE','Where the Crawdads Sing');
INSERT INTO Book VALUES (24, 15, '978-1524715353','AVAILABLE', 'Everything Everything');
INSERT INTO Book VALUES (25, 30, '978-0316772366', 'AVAILABLE','The Lord of the Flies');

INSERT INTO BOOK_AUTHOR VALUES (1, 2);
INSERT INTO BOOK_AUTHOR VALUES (2, 3);
INSERT INTO BOOK_AUTHOR VALUES (3, 4);
INSERT INTO BOOK_AUTHOR VALUES (4, 5);
INSERT INTO BOOK_AUTHOR VALUES (5, 6);
INSERT INTO BOOK_AUTHOR VALUES (6, 7);
INSERT INTO BOOK_AUTHOR VALUES (7, 8);
INSERT INTO BOOK_AUTHOR VALUES (8, 9);
INSERT INTO BOOK_AUTHOR VALUES (9, 10);
INSERT INTO BOOK_AUTHOR VALUES (11, 12);
INSERT INTO BOOK_AUTHOR VALUES (12, 13);
INSERT INTO BOOK_AUTHOR VALUES (13, 14);
INSERT INTO BOOK_AUTHOR VALUES (14, 15);
INSERT INTO BOOK_AUTHOR VALUES (15, 16);
INSERT INTO BOOK_AUTHOR VALUES (16, 17);
INSERT INTO BOOK_AUTHOR VALUES (17, 18);
INSERT INTO BOOK_AUTHOR VALUES (18, 19);
INSERT INTO BOOK_AUTHOR VALUES (19, 20);
INSERT INTO BOOK_AUTHOR VALUES (20, 21);
INSERT INTO BOOK_AUTHOR VALUES (21, 22);
INSERT INTO BOOK_AUTHOR VALUES (22, 23);
INSERT INTO BOOK_AUTHOR VALUES (23, 24);
INSERT INTO BOOK_AUTHOR VALUES (24, 25);
INSERT INTO BOOK_AUTHOR VALUES (25, 2);
INSERT INTO BOOK_AUTHOR VALUES (26, 3);
INSERT INTO BOOK_AUTHOR VALUES (27, 4);
INSERT INTO BOOK_AUTHOR VALUES (28, 5);
INSERT INTO BOOK_AUTHOR VALUES (29, 6);
INSERT INTO BOOK_AUTHOR VALUES (30, 7);
INSERT INTO BOOK_AUTHOR VALUES (31, 8);
INSERT INTO BOOK_AUTHOR VALUES (32, 9);
INSERT INTO BOOK_AUTHOR VALUES (33, 10);
INSERT INTO BOOK_AUTHOR VALUES (34, 11);
INSERT INTO BOOK_AUTHOR VALUES (35, 12);
INSERT INTO BOOK_AUTHOR VALUES (36, 13);
INSERT INTO BOOK_AUTHOR VALUES (37, 14);
INSERT INTO BOOK_AUTHOR VALUES (38, 15);
INSERT INTO BOOK_AUTHOR VALUES (39, 16);
INSERT INTO BOOK_AUTHOR VALUES (40, 17);
