INSERT INTO AUTHOR VALUES (1, 'United States', 'author1@example.com', 'Author One');
INSERT INTO AUTHOR VALUES (2, 'Canada', 'author2@example.com', 'Author Two');
INSERT INTO AUTHOR VALUES (3, 'United Kingdom', 'author3@example.com', 'Author Three');
INSERT INTO AUTHOR VALUES (4, 'Australia', 'author4@example.com', 'Author Four');
INSERT INTO AUTHOR VALUES (5, 'Germany', 'author5@example.com', 'Author Five');
INSERT INTO AUTHOR VALUES (6, 'France', 'author6@example.com', 'Author Six');
INSERT INTO AUTHOR VALUES (7, 'Japan', 'author7@example.com', 'Author Seven');
INSERT INTO AUTHOR VALUES (8, 'China', 'author8@example.com', 'Author Eight');
INSERT INTO AUTHOR VALUES (9, 'India', 'author9@example.com', 'Author Nine');
INSERT INTO AUTHOR VALUES (10, 'Brazil', 'author10@example.com', 'Author Ten');
INSERT INTO AUTHOR VALUES (11, 'Argentina', 'author11@example.com', 'Author Eleven');
INSERT INTO AUTHOR VALUES (12, 'Colombia', 'author12@example.com', 'Author Twelve');
INSERT INTO AUTHOR VALUES (13, 'Netherlands', 'author13@example.com', 'Author Thirteen');
INSERT INTO AUTHOR VALUES (14, 'Spain', 'author14@example.com', 'Author Fourteen');
INSERT INTO AUTHOR VALUES (15, 'Sweden', 'author15@example.com', 'Author Fifteen');
INSERT INTO AUTHOR VALUES (16, 'Italy', 'author16@example.com', 'Author Sixteen');
INSERT INTO AUTHOR VALUES (17, 'Russia', 'author17@example.com', 'Author Seventeen');
INSERT INTO AUTHOR VALUES (18, 'South Korea', 'author18@example.com', 'Author Eighteen');
INSERT INTO AUTHOR VALUES (19, 'Mexico', 'author19@example.com', 'Author Nineteen');
INSERT INTO AUTHOR VALUES (20, 'Indonesia', 'author20@example.com', 'Author Twenty');
INSERT INTO AUTHOR VALUES (21, 'Nigeria', 'author21@example.com', 'Author Twenty One');
INSERT INTO AUTHOR VALUES (22, 'Egypt', 'author22@example.com', 'Author Twenty Two');
INSERT INTO AUTHOR VALUES (23, 'Philippines', 'author23@example.com', 'Author Twenty Three');
INSERT INTO AUTHOR VALUES (24, 'Vietnam', 'author24@example.com', 'Author Twenty Four');
INSERT INTO AUTHOR VALUES (25, 'Bangladesh', 'author25@example.com', 'Author Twenty Five');
INSERT INTO AUTHOR VALUES (26, 'Turkey', 'author26@example.com', 'Author Twenty Six');
INSERT INTO AUTHOR VALUES (27, 'Thailand', 'author27@example.com', 'Author Twenty Seven');
INSERT INTO AUTHOR VALUES (28, 'Poland', 'author28@example.com', 'Author Twenty Eight');
INSERT INTO AUTHOR VALUES (29, 'Argentina', 'author29@example.com', 'Author Twenty Nine');
INSERT INTO AUTHOR VALUES (30, 'Ukraine', 'author30@example.com', 'Author Thirty');
INSERT INTO AUTHOR VALUES (31, 'Saudi Arabia', 'author31@example.com', 'Author Thirty One');
INSERT INTO AUTHOR VALUES (32, 'Malaysia', 'author32@example.com', 'Author Thirty Two');
INSERT INTO AUTHOR VALUES (33, 'Czech Republic', 'author33@example.com', 'Author Thirty Three');
INSERT INTO AUTHOR VALUES (34, 'Belgium', 'author34@example.com', 'Author Thirty Four');
INSERT INTO AUTHOR VALUES (35, 'Greece', 'author35@example.com', 'Author Thirty Five');
INSERT INTO AUTHOR VALUES (36, 'Portugal', 'author36@example.com', 'Author Thirty Six');
INSERT INTO AUTHOR VALUES (37, 'Hungary', 'author37@example.com', 'Author Thirty Seven');
INSERT INTO AUTHOR VALUES (38, 'Switzerland', 'author38@example.com', 'Author Thirty Eight');
INSERT INTO AUTHOR VALUES (39, 'Austria', 'author39@example.com', 'Author Thirty Nine');
INSERT INTO AUTHOR VALUES (40, 'United Arab Emirates', 'author40@example.com', 'Author Forty');